/*!
 * Board Game Places — Detail-Panel Renderer (V12 Render)
 * Version: 1.12.2
 * Project: https://boardgameplaces.com
 * Repo: https://github.com/urbanchallenger/boardgameplaces-js
 * License: MIT
 *
 * Section-hide logic: when a CMS field is empty, the corresponding detail-panel section is hidden instead of showing an empty label. Filters out example.com URLs and DE/Deutschland country values.
 */
(function(){function R(f){if(document.readyState!=='loading')f();else document.addEventListener('DOMContentLoaded',f)}R(function(){var M=window.BGP_LBL,G=window.BGP_GET,c=window.BGP_CSV,s=window.BGP_SLG,sp=window.BGP_SP;function $(i){return document.getElementById(i)}function P(e,v){if(e)e.style.display=v?'':'none'}function S(i,v,sub){var e=$(i);if(!e)return;e.textContent=v||'';P(sub?e:e.parentElement,v)}function f(k){if(!k)return;var d=k.dataset,gl=+G(k,'game-level',d.gameLevel)||0,fl=+G(k,'food-level',d.foodLevel)||0,pr=(G(k,'pricing',d.pricing)||'').toLowerCase();S('detail-desc',G(k,'description',d.description));S('detail-game',gl?M.G[gl]:'');S('detail-game-claim',G(k,'games-count-claim',d.gamesCountClaim),1);S('detail-food',fl?M.FD[fl]:'');S('detail-pricing',pr?M.P[pr]||pr:'');S('detail-pricing-detail',G(k,'pricing-detail',d.pricingDetail),1);S('detail-hours',G(k,'hours',d.hours));var a=$('detail-address');if(a){var t=G(k,'address',d.address)||'',rg=G(k,'region',d.region),co=G(k,'country',d.country);if(rg)t+=' · '+rg;if(co&&co!=='Deutschland'&&co!=='DE')t+=' · '+co;a.textContent=t;P(a.parentElement,t)}var w=$('detail-web');if(w){var u=G(k,'web',d.web),ok=u&&u.indexOf('example.com')<0;w.textContent=ok?u.replace(/^https?:\/\//,''):'';if(ok)w.href=u.indexOf('http')===0?u:'https://'+u;else w.removeAttribute('href');P(w.parentElement,ok)}var m=$('detail-meta');if(m){m.innerHTML='';var fr=s(G(k,'frequency',d.frequency));if(fr)m.appendChild(sp('detail-frequency-badge',M.F[fr]||fr));c(G(k,'setting',d.setting)).forEach(function(x){m.appendChild(sp('detail-setting-tag',M.S[s(x)]||x))})}var p=$('detail-pillen');if(p){p.innerHTML='';c(G(k,'languages',d.languages)).forEach(function(l){p.appendChild(sp('detail-lang-pill',M.L[l.toLowerCase()]||l.toUpperCase()))});c(G(k,'accessibility',d.accessibility)).forEach(function(x){p.appendChild(sp('detail-acc-tag',M.A[x]||x))})}}document.querySelectorAll('.location-card').forEach(function(k){k.addEventListener('click',function(){setTimeout(function(){f(k)},30)})})});})();